*** Variables ***
# Android

#Application Bitbar Sample
#${appPackage}       com.bitbar.testdroid
#${appActivity}      com.bitbar.testdroid.BitbarSampleApplicationActivity

#Application Bitbar Sample
${appPackageBitbar}       com.bitbar.testdroid
${appActivityBitbar}      com.bitbar.testdroid.BitbarSampleApplicationActivity

#Application API Demos
${appPackageApi}       io.appium.android.apis
${appActivityApi}      io.appium.android.apis.ApiDemos

# IOS
${bundleId}         TODO
